---
variables:
  TF_MIN_VERSION: "1.3"
  AZURERM_PROVIDER_MIN_VERSION: "3.39"

include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'
  - project: 'claranet/projects/cloud/azure/terraform/ci'
    ref: master
    file: '/pipeline.yml'
...
